import Head from 'next/head'
import Image from 'next/image'
import Form from '../components/Form'
import styled from 'styled-components'
import React, { useState } from 'react';


const StyledMain = styled.div`

background: #4C4C4C;

`;

export default function Home() {

  const [addressArray, setArray] = useState([]);

  return (
    <StyledMain>
        <Head>
          <title>BloEx Certificates</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="container">
          <div className="row justify-content-center align-items-center vh-100">
            <div className="col-10">
              <Form addressArray={addressArray} setArray={setArray}/>
            </div>
          </div>
        </div>
    </StyledMain>
  )
}
