import Head from 'next/head'
import Image from 'next/image'
import { Form } from '../components/Form'
import styled from 'styled-components'
import React, { useState } from 'react';
import { ConnectButton } from '@web3uikit/web3';


const StyledMain = styled.div`
  background: var(--black);
  margin: 0;

`;

export default function Home() {

  const [addressArray, setArray] = useState([]);

  return (
    <StyledMain className='container-fluid'>
      <div className="row justify-content-center align-items-center vh-100">
        <div className="col-10">
          <Head>
            <title>NFT Minter</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Form addressArray={addressArray} setArray={setArray}/>
          <ConnectButton moralisAuth={false} />
        </div>
      </div>
    </StyledMain>
  )
}
